### ISSUE TITLE
this code is not relevent now

### ISSUE THREAD

**Issue by ANU197** [ogomez92/eleven_labsrt#1]
as there is change in elevencodes documentation, code is not relevent

src/elevenlabs_service.py => Line 23 elevenlabs.set_api_key(self.api_key)

this is showing error

**Comment by ogomez92** [comment]
Hello,
Thanks so much for flagging this.
I have updated the code to work with the latest elevenlabs API.

Try it again and see if it works, thanks.

**Comment by ANU197** [comment]
Thank you very much @ogomez92 to fix this overnight, this is really exciting tool.
I can confirm, this is working now.

**Comment by ogomez92** [comment]
Overnight is right, I couldn't sleep it was like 4 AM and I'm hung over. lol

**Comment by M-FTheo** [comment]
Hey man, this is such an amazing tool, but i cant get it to work since im a beginner in python
I was able to install all requirements and get my api from eleven, but now i just dont know what to do, could you help me, please? thanks for making this

**Comment by M-FTheo** [comment]
py main.py -i leg.srt -v Brian -o saida.mp3

with this i was able but the output (saida.mp3) is five minutes long :/

my srt looks like this:
1
00:00:00,140 --> 00:00:00,400
When

2
00:00:00,401 --> 00:00:00,580
this

3
00:00:00,581 --> 00:00:00,820
woman

4
00:00:00,821 --> 00:00:01,061
returned

5
00:00:01,062 --> 00:00:01,321
from a

6
00:00:01,322 --> 00:00:01,681
month-long
